#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
#ifndef AUTOPAYSDK_SWIFT_H
#define AUTOPAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AutopaySdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class APError;

SWIFT_PROTOCOL("_TtP10AutopaySdk14APBaseCallback_")
@protocol APBaseCallback
- (void)errorDidOccur:(APError * _Nonnull)error;
@end

@class NSCoder;

SWIFT_CLASS("_TtC10AutopaySdk10APBaseView")
@interface APBaseView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
@end

@class UIActivityIndicatorView;
@protocol APPaymentMethodViewDelegate;
@class NSString;
@class UIColor;
@class APGlobalStyle;

SWIFT_CLASS("_TtC10AutopaySdk19APPaymentMethodView")
@interface APPaymentMethodView : APBaseView <APBaseCallback>
@property (nonatomic, readonly, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
@property (nonatomic, weak) id <APPaymentMethodViewDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable contentHeaderTitle;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic) BOOL isContentVisible;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalHeaderTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable regulationTextStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
- (void)hideRegulations;
- (void)hideLoadingMode;
- (void)errorDidOccur:(APError * _Nonnull)error;
@end

@class UITraitCollection;
@class APGateway;
@class APConfig;

SWIFT_CLASS("_TtC10AutopaySdk14APApplePayView")
@interface APApplePayView : APPaymentMethodView
@property (nonatomic, strong) APGlobalStyle * _Nullable globalBackButtonStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (void)prepareForInterfaceBuilder;
- (void)set:(APGateway * _Nonnull)gateway config:(APConfig * _Nonnull)config;
- (void)hideRegulations;
- (void)errorDidOccur:(APError * _Nonnull)error;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk27APPaymentMethodViewDelegate_")
@protocol APPaymentMethodViewDelegate
@optional
- (void)didSelect:(APPaymentMethodView * _Nonnull)paymentMethodView;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk22APApplePayViewDelegate_")
@protocol APApplePayViewDelegate <APPaymentMethodViewDelegate>
- (void)applePayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
@end

@class UIImage;
@class UIScrollView;

SWIFT_CLASS("_TtC10AutopaySdk17APGatewayGridView")
@interface APGatewayGridView : APPaymentMethodView
@property (nonatomic) NSInteger numberOfCellsInRow;
@property (nonatomic) CGFloat cellHeight;
@property (nonatomic) CGColorRef _Nullable cellBorderColor;
@property (nonatomic) CGFloat cellCornerRadius;
@property (nonatomic, strong) UIImage * _Nullable cellPlaceholder;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
- (void)set:(NSArray<APGateway *> * _Nonnull)gatewayList config:(APConfig * _Nonnull)config;
- (void)set:(UIScrollView * _Nonnull)partnerScrollView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AutopaySdk22APBankTransferGridView")
@interface APBankTransferGridView : APGatewayGridView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk30APBankTransferGridViewDelegate_")
@protocol APBankTransferGridViewDelegate <APPaymentMethodViewDelegate>
- (void)bankTransferPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
@end



SWIFT_CLASS("_TtC10AutopaySdk13APBaseDcbView")
@interface APBaseDcbView : APPaymentMethodView
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
- (void)set:(APGateway * _Nonnull)gateway phoneNumber:(NSString * _Nonnull)phoneNumber config:(APConfig * _Nonnull)config;
- (void)hideRegulations;
- (void)hideLoadingMode;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class APGlobalTextFieldStyle;

SWIFT_CLASS("_TtC10AutopaySdk21APBasePaymentCardView")
@interface APBasePaymentCardView : APPaymentMethodView
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable inputLabelTextStyle;
@property (nonatomic, strong) APGlobalTextFieldStyle * _Nullable globalTextFieldStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
@property (nonatomic) CGFloat leftMarginLabels;
@property (nonatomic) CGFloat leftMarginTextFields;
@property (nonatomic) BOOL isNameSectionVisible;
- (void)hideLoadingMode;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end





@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC10AutopaySdk10APBlikView")
@interface APBlikView : APPaymentMethodView
@property (nonatomic) CGFloat codeFontSize;
@property (nonatomic, strong) UIColor * _Nullable codeTextColor;
@property (nonatomic) CGColorRef _Nullable codeActiveBorderColor;
@property (nonatomic) CGColorRef _Nullable codeInactiveBorderColor;
@property (nonatomic, copy) NSString * _Nullable loaderHeaderTitle;
@property (nonatomic, strong) UIColor * _Nullable loaderHeaderColor;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalTextFieldStyle * _Nullable globalTextFieldStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)set:(APGateway * _Nonnull)gateway config:(APConfig * _Nonnull)config;
- (void)hideLoadingMode;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk18APBlikViewDelegate_")
@protocol APBlikViewDelegate
- (void)blikPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
@end

enum APEnvironmentEnum : NSInteger;

SWIFT_CLASS("_TtC10AutopaySdk8APConfig")
@interface APConfig : NSObject
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token serviceId:(NSInteger)serviceId acceptorId:(NSInteger)acceptorId environment:(enum APEnvironmentEnum)environment OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token serviceId:(NSInteger)serviceId acceptorId:(NSInteger)acceptorId environment:(enum APEnvironmentEnum)environment contextPath:(NSString * _Nonnull)contextPath OBJC_DESIGNATED_INITIALIZER;
- (void)updateWithToken:(NSString * _Nonnull)token;
- (void)setGatewayCurrenciesWithCurrencies:(NSArray<NSString *> * _Nonnull)currencies;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APConfigurationError, open) {
  APConfigurationErrorUnparsableTokenError = 0,
  APConfigurationErrorAuthorizationEncryptionError = 1,
  APConfigurationErrorInvalidUrlError = 2,
};
static NSString * _Nonnull const APConfigurationErrorDomain = @"AutopaySdk.APConfigurationError";


SWIFT_CLASS("_TtC10AutopaySdk10APCurrency")
@interface APCurrency : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10AutopaySdk19APDcbActivationView")
@interface APDcbActivationView : APBaseDcbView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk17APDcbViewDelegate_")
@protocol APDcbViewDelegate <APPaymentMethodViewDelegate>
- (void)dcbPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
@end

typedef SWIFT_ENUM(NSInteger, APEnvironmentEnum, open) {
  APEnvironmentEnumProd = 0,
  APEnvironmentEnumDev = 1,
};

enum APErrorEnum : NSInteger;

SWIFT_CLASS("_TtC10AutopaySdk7APError")
@interface APError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable message;
@property (nonatomic, readonly) enum APErrorEnum status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APErrorEnum, open) {
  APErrorEnumBankDisabled = 0,
  APErrorEnumBlockMultipleTransactions = 1,
  APErrorEnumBlockPaidTransactions = 2,
  APErrorEnumInsufficientStartAmount = 3,
  APErrorEnumOutdatedError = 4,
  APErrorEnumInternalServerError = 5,
  APErrorEnumConnectionError = 6,
  APErrorEnumGeneralError = 7,
  APErrorEnumParsingError = 8,
  APErrorEnumEmptyGatewaysError = 9,
  APErrorEnumInvalidCallbackError = 10,
  APErrorEnumInvalidUrlError = 11,
  APErrorEnumNotConfirmedError = 12,
  APErrorEnumEmptyViewError = 13,
  APErrorEnumEmptyTransactionError = 14,
};

enum APEventEnum : NSInteger;

SWIFT_CLASS("_TtC10AutopaySdk7APEvent")
@interface APEvent : NSObject
@property (nonatomic, readonly) enum APEventEnum status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APEventEnum, open) {
  APEventEnumPageLoaded = 0,
  APEventEnumContentLoaded = 1,
  APEventEnumCanceled = 2,
  APEventEnumLaterClick = 3,
};

enum APGatewayType : NSInteger;

SWIFT_CLASS("_TtC10AutopaySdk9APGateway")
@interface APGateway : NSObject
@property (nonatomic, readonly) NSInteger gatewayId;
@property (nonatomic, readonly, copy) NSString * _Nullable gatewayName;
@property (nonatomic, readonly) enum APGatewayType gatewayType;
@property (nonatomic, readonly, copy) NSString * _Nullable bankName;
@property (nonatomic, readonly, copy) NSString * _Nullable iconUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable state;
@property (nonatomic, readonly, copy) NSString * _Nullable stateDate;
@property (nonatomic, readonly, copy) NSString * _Nullable gatewayDescription;
@property (nonatomic, readonly, copy) NSArray<APCurrency *> * _Nullable currencyList;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (BOOL)theSame:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end



@interface APGateway (SWIFT_EXTENSION(AutopaySdk)) <NSCoding>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
@end

@class APPaymentCardView;
@protocol APGatewayCategoriesViewDelegate;

SWIFT_CLASS("_TtC10AutopaySdk23APGatewayCategoriesView")
@interface APGatewayCategoriesView : APBaseView
@property (nonatomic, weak) IBOutlet APBlikView * _Null_unspecified blikView;
@property (nonatomic, weak) IBOutlet APBankTransferGridView * _Null_unspecified bankTransferGridView;
@property (nonatomic, weak) IBOutlet APPaymentCardView * _Null_unspecified paymentCardView;
@property (nonatomic, weak) IBOutlet APBaseDcbView * _Null_unspecified dcbView;
@property (nonatomic, weak) IBOutlet APApplePayView * _Null_unspecified applePayView;
@property (nonatomic, weak) id <APGatewayCategoriesViewDelegate> _Nullable delegate;
@property (nonatomic, strong) UIColor * _Nullable borderColor;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalHeaderTextStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalRegulationTextStyle;
@property (nonatomic, strong) APGlobalTextFieldStyle * _Nullable globalTextFieldStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalMainButtonStyle;
@property (nonatomic, strong) APGlobalStyle * _Nullable globalBackButtonStyle;
@property (nonatomic, strong) UIColor * _Nullable globalColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
- (void)layoutSubviews;
- (void)setData:(NSArray<APGateway *> * _Nonnull)gatewayList config:(APConfig * _Nonnull)config;
- (void)resetAllViews;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk25APPaymentCardViewDelegate_")
@protocol APPaymentCardViewDelegate <APPaymentMethodViewDelegate>
- (void)paymentCardPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
@end


@interface APGatewayCategoriesView (SWIFT_EXTENSION(AutopaySdk)) <APApplePayViewDelegate, APBankTransferGridViewDelegate, APBlikViewDelegate, APPaymentCardViewDelegate>
- (void)blikPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)bankTransferPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)paymentCardPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)applePayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)didSelect:(APPaymentMethodView * _Nonnull)paymentMethodView;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk31APGatewayCategoriesViewDelegate_")
@protocol APGatewayCategoriesViewDelegate
@optional
- (void)bankTransferPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)blikPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)applePayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)paymentCardPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)dcbPayDidClickWith:(APGateway * _Nonnull)gateway and:(NSDictionary<NSString *, NSString *> * _Nonnull)params;
- (void)categoryDidSelectWith:(enum APGatewayType)gatewayType;
- (void)categoryDidDeselect;
@end


SWIFT_CLASS("_TtC10AutopaySdk23APGatewayCategoryHeader")
@interface APGatewayCategoryHeader : APBaseView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
@end


@class UICollectionView;
@class UICollectionViewLayout;
@class NSIndexPath;

@interface APGatewayGridView (SWIFT_EXTENSION(AutopaySdk)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewCell;

@interface APGatewayGridView (SWIFT_EXTENSION(AutopaySdk)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_PROTOCOL("_TtP10AutopaySdk21APGatewayListCallback_")
@protocol APGatewayListCallback <APBaseCallback>
- (void)dataDidReceiveWithGatewayList:(NSArray<APGateway *> * _Nonnull)gatewayList;
@end

typedef SWIFT_ENUM(NSInteger, APGatewayType, open) {
  APGatewayTypeBlik = 0,
  APGatewayTypeAutoPaymentBlik = 1,
  APGatewayTypePbl = 2,
  APGatewayTypeFastTransaction = 3,
  APGatewayTypeCard = 4,
  APGatewayTypeAutoPaymentCard = 5,
  APGatewayTypeInstallments = 6,
  APGatewayTypePis = 7,
  APGatewayTypeAis = 8,
  APGatewayTypeOtp = 9,
  APGatewayTypeMasterPass = 10,
  APGatewayTypeGooglePay = 11,
  APGatewayTypeVisaCheckout = 12,
  APGatewayTypeApplePay = 13,
  APGatewayTypeBankTransfer = 14,
  APGatewayTypeAutoPaymentDcb = 15,
  APGatewayTypeUndefined = 16,
};

@class UIFont;

SWIFT_CLASS("_TtC10AutopaySdk13APGlobalStyle")
@interface APGlobalStyle : NSObject
- (nonnull instancetype)initWithFont:(UIFont * _Nonnull)font textColor:(UIColor * _Nonnull)textColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFont:(UIFont * _Nonnull)font textColor:(UIColor * _Nonnull)textColor backgroundColor:(UIColor * _Nonnull)backgroundColor cornerRadius:(CGFloat)cornerRadius size:(CGSize)size;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class APLayerStyle;

SWIFT_CLASS("_TtC10AutopaySdk22APGlobalTextFieldStyle")
@interface APGlobalTextFieldStyle : NSObject
- (nonnull instancetype)initWithDefaultTextAttributes:(NSDictionary<NSAttributedStringKey, id> * _Nonnull)defaultTextAttributes layer:(APLayerStyle * _Nonnull)layer OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10AutopaySdk12APLayerStyle")
@interface APLayerStyle : NSObject
@property (nonatomic) CGColorRef _Nullable backgroundColor;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGColorRef _Nullable borderColor;
@property (nonatomic) float opacity;
@property (nonatomic) CGColorRef _Nullable shadowColor;
@property (nonatomic) float shadowOpacity;
@property (nonatomic) CGSize shadowOffset;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGPathRef _Nullable shadowPath;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AutopaySdk5APLog")
@interface APLog : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL SHOW_LOG;)
+ (BOOL)SHOW_LOG SWIFT_WARN_UNUSED_RESULT;
+ (void)setSHOW_LOG:(BOOL)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AutopaySdk7APParam")
@interface APParam : NSObject
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name value:(NSString * _Nonnull)value additionalAttributes:(NSDictionary<NSString *, NSString *> * _Nonnull)additionalAttributes;
- (void)addAdditionalAttributeWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10AutopaySdk27APPaymentCardActivationView")
@interface APPaymentCardActivationView : APBasePaymentCardView
@property (nonatomic, copy) NSString * _Nullable activationText;
@property (nonatomic, strong) APGlobalStyle * _Nullable activationTextStyle;
- (void)set:(APGateway * _Nonnull)gateway config:(APConfig * _Nonnull)config;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10AutopaySdk17APPaymentCardView")
@interface APPaymentCardView : APBasePaymentCardView
- (void)set:(NSArray<APGateway *> * _Nonnull)gateways config:(APConfig * _Nonnull)config;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC10AutopaySdk9APProduct")
@interface APProduct : NSObject
- (nonnull instancetype)initWithSubAmount:(NSString * _Nonnull)subAmount params:(NSArray<APParam *> * _Nonnull)params OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSubAmount:(NSString * _Nonnull)subAmount param:(APParam * _Nonnull)param;
- (void)addParam:(APParam * _Nonnull)param;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10AutopaySdk13APProductList")
@interface APProductList : NSObject
- (nonnull instancetype)initWithProductList:(NSArray<APProduct *> * _Nonnull)productList OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithProduct:(APProduct * _Nonnull)product;
- (void)addProductWithProduct:(APProduct * _Nonnull)product;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APRecurringAcceptanceStateEnum, open) {
  APRecurringAcceptanceStateEnumAccepted = 0,
  APRecurringAcceptanceStateEnumNotApplicable = 1,
  APRecurringAcceptanceStateEnumForce = 2,
  APRecurringAcceptanceStateEnumUnknown = 3,
};

typedef SWIFT_ENUM(NSInteger, APRecurringActionEnum, open) {
  APRecurringActionEnumInitWithPayment = 0,
  APRecurringActionEnumInitWithRefund = 1,
  APRecurringActionEnumAuto = 2,
  APRecurringActionEnumDeactivate = 3,
  APRecurringActionEnumUnknown = 4,
};


SWIFT_CLASS("_TtC10AutopaySdk13APRequestData")
@interface APRequestData : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum APResultEnum : NSInteger;

SWIFT_CLASS("_TtC10AutopaySdk8APResult")
@interface APResult : NSObject
@property (nonatomic, readonly) enum APResultEnum status;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, APResultEnum, open) {
  APResultEnumSuccess = 0,
  APResultEnumSuccessMany = 1,
  APResultEnumPending = 2,
  APResultEnumFailure = 3,
};


SWIFT_PROTOCOL("_TtP10AutopaySdk21APTransactionCallback_")
@protocol APTransactionCallback <APBaseCallback>
- (void)transactionDidFinishWith:(APResult * _Nullable)result;
- (void)transactionEventDidOccur:(APEvent * _Nonnull)event;
@end

@class PKPaymentToken;

SWIFT_CLASS("_TtC10AutopaySdk17APTransactionData")
@interface APTransactionData : APRequestData
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount with:(NSString * _Nonnull)orderId;
- (NSString * _Nonnull)getOrderId SWIFT_WARN_UNUSED_RESULT;
- (NSDictionary<NSString *, NSString *> * _Nonnull)getParams SWIFT_WARN_UNUSED_RESULT;
- (void)setCustomerEmail:(NSString * _Nonnull)customerEmail;
- (void)setCustomerPhone:(NSString * _Nonnull)customerPhone;
- (void)setGatewayId:(NSInteger)gatewayId;
- (void)setRecurringAction:(enum APRecurringActionEnum)recurringAction;
- (void)setRecurringAcceptanceState:(enum APRecurringAcceptanceStateEnum)recurringAcceptanceState;
- (void)addParams:(NSDictionary<NSString *, NSString *> * _Nonnull)customParams;
- (void)addParamWithValue:(NSString * _Nonnull)value key:(NSString * _Nonnull)key;
- (void)setProductList:(APProductList * _Nonnull)products;
- (void)setApplePayPaymentToken:(PKPaymentToken * _Nonnull)paymentToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10AutopaySdk17APTransactionView")
@interface APTransactionView : APBaseView
- (nonnull instancetype)init;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForInterfaceBuilder;
@end

@class NSURLRequest;
@class WKNavigation;
@class WKWebViewConfiguration;

SWIFT_CLASS("_TtC10AutopaySdk9APWebView")
@interface APWebView : WKWebView <UIScrollViewDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
- (WKNavigation * _Nullable)loadRequest:(NSURLRequest * _Nonnull)request SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC10AutopaySdk7Autopay")
@interface Autopay : NSObject
+ (NSString * _Nullable)getSdkVersion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConfig:(APConfig * _Nonnull)config OBJC_DESIGNATED_INITIALIZER;
+ (BOOL)continueTransactionWithTransactionCallback:(id <APTransactionCallback> _Nonnull)transactionCallback url:(NSString * _Nonnull)url view:(APTransactionView * _Nonnull)view error:(NSError * _Nullable * _Nullable)error;
- (void)startTransactionWithTransactionCallback:(id <APTransactionCallback> _Nonnull)transactionCallback transactionData:(APTransactionData * _Nonnull)transactionData view:(APTransactionView * _Nonnull)view;
- (void)getGatewayListWithGatewayCallback:(id <APGatewayListCallback> _Nonnull)gatewayCallback;
- (void)getGatewayListWithGatewayCallback:(id <APGatewayListCallback> _Nonnull)gatewayCallback view:(APGatewayCategoriesView * _Nonnull)view;
- (void)startBlikTransactionWithTransactionCallback:(id <APTransactionCallback> _Nonnull)transactionCallback transactionData:(APTransactionData * _Nonnull)transactionData;
- (void)startBlikTransactionWithTransactionCallback:(id <APTransactionCallback> _Nonnull)transactionCallback transactionData:(APTransactionData * _Nonnull)transactionData view:(APBlikView * _Nonnull)view;
- (void)startApplePayTransactionWithTransactionData:(APTransactionData * _Nonnull)transactionData transactionCompletionHandler:(void (^ _Nonnull)(APResult * _Nullable, APError * _Nullable))transactionCompletionHandler;
- (void)getTransactionStatusWithTransactionCallback:(id <APTransactionCallback> _Nonnull)transactionCallback orderId:(NSString * _Nonnull)orderId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
